# Generated by Django 4.2 on 2023-08-09 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
